language: objective-c
osx_image: xcode7.3

install:
  - bundle install

env:
  - TTT_LANG="Arabic"
  - TTT_LANG="Catalan"
  - TTT_LANG="Chinese-Simplified"
  - TTT_LANG="Chinese-Traditional"
  - TTT_LANG="Czech"
  - TTT_LANG="Danish"
  - TTT_LANG="Dutch"
  - TTT_LANG="English"
  - TTT_LANG="French"
  - TTT_LANG="German"
  - TTT_LANG="Greek"
  - TTT_LANG="Hebrew"
  - TTT_LANG="Hungarian"
  - TTT_LANG="Indonesian"
  - TTT_LANG="Italian"
  - TTT_LANG="Japanese"
  - TTT_LANG="Korean"
  - TTT_LANG="Malay"
  - TTT_LANG="Norwegian-Bokmal"
  - TTT_LANG="Norwegian-Nynorsk"
  - TTT_LANG="Polish"
  - TTT_LANG="Portuguese"
  - TTT_LANG="Portuguese-Brazil"
  - TTT_LANG="Romanian"
  - TTT_LANG="Russian"
  - TTT_LANG="Spanish"
  - TTT_LANG="Swedish"
  - TTT_LANG="Thai"
  - TTT_LANG="Turkish"
  - TTT_LANG="Ukrainian"
  - TTT_LANG="Vietnamese"
  - TTT_COMMAND="rake integration:cocoapods_ios"
  - TTT_COMMAND="rake integration:cocoapods_ios_static"
  - TTT_COMMAND="rake integration:cocoapods_osx"
  - TTT_COMMAND="rake integration:carthage_ios"
  - TTT_COMMAND="rake integration:carthage_osx"
  - TTT_COMMAND="pod lib lint"
  - TTT_COMMAND="pod lib lint --use-libraries"

script:
  - test -n "$TTT_LANG" && rake spec:$TTT_LANG || bundle exec $TTT_COMMAND

after_success:
  - test -n "$TTT_LANG" && bundle exec slather coverage --scheme="$TTT_LANG" --build-directory="build/DerivedData/$TTT_LANG" --coveralls
